language: python
python:
    - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
    - git clone https://github.com/phanrahan/magma.git
    - if [[ $TRAVIS_BRANCH == 'coreir-dev' ]]; then git -C magma checkout coreir-dev; fi
    - pip install -e magma
    - source magma/.travis/install_coreir.sh

install:
    - pip install pytest-cov
    - pip install fabricate delegator.py
    - pip install -e .

script:
    - ./scripts/run_tests.sh
